version: '3'
services:
  opas:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        git_email: ${git_email}
        git_name: ${git_name}
    container_name: opas
    volumes:
      - ./:/opas
    working_dir: /opas
    tty: true
    restart: always