services:
  opas:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        git_email: ${git_email}
        git_name: ${git_name}
    container_name: opas
    volumes:
      - ./:/opas
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    working_dir: /opas
    tty: true
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf