services:
  opas:
    build:
      context: .
      dockerfile: local/Dockerfile
      args:
        git_email: ${git_email}
        git_name: ${git_name}
    container_name: opas
    working_dir: /opas
    volumes:
      - ./:/opas
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    tty: true
    init: true
    command: redis-server /usr/local/etc/redis/redis.conf