services:
  selenium:
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
      - 7900:7900
    container_name: selenium
  opas:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        git_email: ${git_email}
        git_name: ${git_name}
    container_name: opas
    volumes:
      - ./:/opas
    working_dir: /opas
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true
    restart: always